services:
  # app:
  #   container_name: pawclock
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "4000:4000" # Expose Phoenix app on port 4000
  #   env_file:
  #     - .env
  #   # environment:
  #   #   DATABASE_URL: "ecto://postgres:postgres@db:5432/pawclock_dev"
  #   tty: true
  #   stdin_open: true
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/app # Mount the current directory to /app in the container

  db:
    container_name: pawclock_db
    image: postgres:latest
    ports:
      - "5432:5432" # Expose PostgreSQL on port 5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080" # Expose Adminer on port 8080
    depends_on:
      - db
volumes:
  postgres_data: