# Generated by Django 5.2 on 2025-04-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_pawclock", "0003_owner_pet_many_to_many"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DayCareSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_in", models.DateTimeField(auto_now_add=True, null=True)),
                ("check_out", models.DateTimeField()),
                (
                    "check_in_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_sessions",
                        to="app_pawclock.owner",
                    ),
                ),
                (
                    "check_in_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_in_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "check_out_owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_out_sessions",
                        to="app_pawclock.owner",
                    ),
                ),
                (
                    "check_out_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_out_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="day_care_sessions",
                        to="app_pawclock.pet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Day Care Session",
                "verbose_name_plural": "Day Care Sessions",
            },
        ),
    ]
